# Generated by Django 6.0.4 on 2026-04-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
