# Generated by Django 6.0.4 on 2026-04-28 07:55

import apps.models.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.models.managers.CustomUserManager()),
            ],
        ),
    ]
