# Generated by Django 6.0.4 on 2026-04-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_category_tag_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
